### ISSUE TITLE
Error raised by get_sprite_contacts.py in #5 Heatmaps

### ISSUE THREAD

**Issue by tangyitao** [GuttmanLab/sprite-pipeline#3]
I have a problem with executing get_sprite_contacts.py and I got OSError: [Errno 8] Exec format error: '../sprite-pipeline/scripts/HiCorrector_1.2/bin/ic'. I did not use Snakemake. Detailed command line and error message are as follows:

$ python ../sprite-pipeline/scripts/python/get_sprite_contacts.py \
> --raw_contacts raw_contacts.txt --biases bias_contacts.txt --iced iced_contacts.txt \
> --clusters input.clusters --output final.txt \
> --chromosome genome \
> --hicorrector ../sprite-pipeline/scripts/HiCorrector_1.2/bin/ic

Traceback (most recent call last):
  File "../sprite-pipeline/scripts/python/get_sprite_contacts.py", line 123, in <module>
    main()
  File "../sprite-pipeline/scripts/python/get_sprite_contacts.py", line 24, in main
    hicorrector_path = args.hicorrector)
  File " <full path to> /sprite-pipeline/scripts/python/contact.py", line 332, in ice_raw_contacts
    iterations = iterations)
  File " <full path to> /sprite-pipeline/scripts/python/contact.py", line 387, in calculate_bias_factors
    str(iterations), skip_first_row, skip_first_column, bias_file])
  File "/opt/anaconda3/lib/python3.7/subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/anaconda3/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/opt/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '../sprite-pipeline/scripts/HiCorrector_1.2/bin/ic'

**Comment by tangyitao** [comment]
The issue is resolved by compiling HiCorrector with openmpi in Mac OS.
